import type { EducationalArchitecture } from '../types';

export const PRESET_ARCHITECTURES: Record<string, EducationalArchitecture> = {
  traditional: {
    id: 'traditional',
    name: 'Traditional / Standardized Model',
    presetId: 'traditional',
    description: 'High exam reliance, fixed grade progression, rigid standardized curriculum, top-down instruction.',
    examWeightPct: 70,
    homeworkHoursPerDay: 3.5,
    aiIntegrationLevel: 10,
    studentAutonomyPct: 15,
    teacherAutonomyPct: 30,
    classSize: 32,
    masteryThresholdPct: 60,
    fundingPerStudentUSD: 8500,
    wellbeingFocusPct: 30,
    collaborativeLearningPct: 25,
    interdisciplinaryPct: 20
  },

  montessori: {
    id: 'montessori',
    name: 'Montessori / Self-Directed Model',
    presetId: 'montessori',
    description: 'Student-led discovery, low exam pressure, hands-on learning, mixed-age classrooms, intrinsic motivation focus.',
    examWeightPct: 10,
    homeworkHoursPerDay: 0.5,
    aiIntegrationLevel: 25,
    studentAutonomyPct: 85,
    teacherAutonomyPct: 80,
    classSize: 22,
    masteryThresholdPct: 85,
    fundingPerStudentUSD: 14000,
    wellbeingFocusPct: 90,
    collaborativeLearningPct: 75,
    interdisciplinaryPct: 80
  },

  finnish: {
    id: 'finnish',
    name: 'Finnish / Holistic Equality Model',
    presetId: 'finnish',
    description: 'Minimal standardized exams, high teacher autonomy, zero homework pressure, strong focus on social equality and wellbeing.',
    examWeightPct: 15,
    homeworkHoursPerDay: 0.8,
    aiIntegrationLevel: 40,
    studentAutonomyPct: 65,
    teacherAutonomyPct: 95,
    classSize: 18,
    masteryThresholdPct: 75,
    fundingPerStudentUSD: 16500,
    wellbeingFocusPct: 95,
    collaborativeLearningPct: 70,
    interdisciplinaryPct: 70
  },

  japanese: {
    id: 'japanese',
    name: 'Japanese / High-Discipline Mastery Model',
    presetId: 'japanese',
    description: 'Rigorous exam prep, high student discipline, community responsibility, strong foundational STEM skills, structured mastery.',
    examWeightPct: 85,
    homeworkHoursPerDay: 4.0,
    aiIntegrationLevel: 30,
    studentAutonomyPct: 20,
    teacherAutonomyPct: 40,
    classSize: 35,
    masteryThresholdPct: 80,
    fundingPerStudentUSD: 11000,
    wellbeingFocusPct: 45,
    collaborativeLearningPct: 50,
    interdisciplinaryPct: 35
  },

  ai_assisted: {
    id: 'ai_assisted',
    name: 'AI-Assisted Adaptive Mastery Engine',
    presetId: 'ai_assisted',
    description: '1-on-1 AI tutoring agents, dynamic pacing per knowledge node, continuous project assessment, high teacher mentoring focus.',
    examWeightPct: 20,
    homeworkHoursPerDay: 1.5,
    aiIntegrationLevel: 95,
    studentAutonomyPct: 75,
    teacherAutonomyPct: 75,
    classSize: 15,
    masteryThresholdPct: 90,
    fundingPerStudentUSD: 15000,
    wellbeingFocusPct: 85,
    collaborativeLearningPct: 65,
    interdisciplinaryPct: 85
  },

  waldorf: {
    id: 'waldorf',
    name: 'Waldorf (Steiner) Education',
    presetId: 'waldorf',
    description: 'Holistic 7-year developmental phases, artistic & practical integration, low digital technology dependency, zero high-stakes exams.',
    examWeightPct: 5,
    homeworkHoursPerDay: 0.5,
    aiIntegrationLevel: 5,
    studentAutonomyPct: 70,
    teacherAutonomyPct: 90,
    classSize: 20,
    masteryThresholdPct: 70,
    fundingPerStudentUSD: 13500,
    wellbeingFocusPct: 95,
    collaborativeLearningPct: 80,
    interdisciplinaryPct: 90
  },

  reggio_emilia: {
    id: 'reggio_emilia',
    name: 'Reggio Emilia Approach',
    presetId: 'reggio_emilia',
    description: 'Student-centered constructivist learning, environment as third teacher, project-based emergent exploration, high peer collaboration.',
    examWeightPct: 5,
    homeworkHoursPerDay: 0.2,
    aiIntegrationLevel: 20,
    studentAutonomyPct: 80,
    teacherAutonomyPct: 85,
    classSize: 16,
    masteryThresholdPct: 75,
    fundingPerStudentUSD: 15500,
    wellbeingFocusPct: 90,
    collaborativeLearningPct: 95,
    interdisciplinaryPct: 85
  },

  ib_diploma: {
    id: 'ib_diploma',
    name: 'International Baccalaureate (IB)',
    presetId: 'ib_diploma',
    description: 'Global interdisciplinary curriculum, Theory of Knowledge (TOK), high academic rigor, community action service, balanced assessment.',
    examWeightPct: 50,
    homeworkHoursPerDay: 3.0,
    aiIntegrationLevel: 60,
    studentAutonomyPct: 60,
    teacherAutonomyPct: 65,
    classSize: 20,
    masteryThresholdPct: 80,
    fundingPerStudentUSD: 18000,
    wellbeingFocusPct: 70,
    collaborativeLearningPct: 75,
    interdisciplinaryPct: 95
  },

  harkness: {
    id: 'harkness',
    name: 'Harkness Discussion Model',
    presetId: 'harkness',
    description: 'Oval-table student-led discussion, zero teacher lecturing, egalitarian inquiry, intensive critical thinking & debate.',
    examWeightPct: 25,
    homeworkHoursPerDay: 2.0,
    aiIntegrationLevel: 35,
    studentAutonomyPct: 75,
    teacherAutonomyPct: 75,
    classSize: 12,
    masteryThresholdPct: 85,
    fundingPerStudentUSD: 21000,
    wellbeingFocusPct: 80,
    collaborativeLearningPct: 100,
    interdisciplinaryPct: 75
  },

  sudbury: {
    id: 'sudbury',
    name: 'Sudbury Democratic School',
    presetId: 'sudbury',
    description: '100% student self-governance, democratic voting on rules, no mandatory syllabus or exams, self-directed play & exploration.',
    examWeightPct: 0,
    homeworkHoursPerDay: 0.0,
    aiIntegrationLevel: 30,
    studentAutonomyPct: 100,
    teacherAutonomyPct: 50,
    classSize: 25,
    masteryThresholdPct: 60,
    fundingPerStudentUSD: 11000,
    wellbeingFocusPct: 100,
    collaborativeLearningPct: 85,
    interdisciplinaryPct: 90
  },

  singapore_mastery: {
    id: 'singapore_mastery',
    name: 'Singapore Math & Mastery System',
    presetId: 'singapore_mastery',
    description: 'Concrete-Pictorial-Abstract framework, 90%+ mastery requirement before progression, high problem-solving rigor, centralized quality.',
    examWeightPct: 75,
    homeworkHoursPerDay: 3.2,
    aiIntegrationLevel: 70,
    studentAutonomyPct: 35,
    teacherAutonomyPct: 50,
    classSize: 30,
    masteryThresholdPct: 90,
    fundingPerStudentUSD: 14500,
    wellbeingFocusPct: 50,
    collaborativeLearningPct: 55,
    interdisciplinaryPct: 45
  },

  prussian_industrial: {
    id: 'prussian_industrial',
    name: 'Prussian Industrial Schooling Model',
    presetId: 'prussian_industrial',
    description: '19th century industrial origin: strict bell schedules, age-sorted cohorts, compliance focus, top-down standardized output.',
    examWeightPct: 90,
    homeworkHoursPerDay: 4.5,
    aiIntegrationLevel: 0,
    studentAutonomyPct: 5,
    teacherAutonomyPct: 15,
    classSize: 45,
    masteryThresholdPct: 50,
    fundingPerStudentUSD: 5500,
    wellbeingFocusPct: 10,
    collaborativeLearningPct: 10,
    interdisciplinaryPct: 10
  },

  south_korea_suneung: {
    id: 'south_korea_suneung',
    name: 'South Korea (Suneung & Hagwon System)',
    presetId: 'south_korea_suneung',
    description: 'Ultra high-stakes Suneung exam, mandatory late-night Hagwon tutoring, high STEM mastery, severe exam stress & burnout.',
    examWeightPct: 95,
    homeworkHoursPerDay: 6.0,
    aiIntegrationLevel: 50,
    studentAutonomyPct: 10,
    teacherAutonomyPct: 25,
    classSize: 30,
    masteryThresholdPct: 92,
    fundingPerStudentUSD: 13000,
    wellbeingFocusPct: 20,
    collaborativeLearningPct: 30,
    interdisciplinaryPct: 25
  },

  germany_dual_vet: {
    id: 'germany_dual_vet',
    name: 'Germany (Dual VET Apprenticeship Model)',
    presetId: 'germany_dual_vet',
    description: '70% practical company apprenticeship + 30% vocational school, high technical mastery, ultra-high hiring placement & automation resilience.',
    examWeightPct: 45,
    homeworkHoursPerDay: 1.5,
    aiIntegrationLevel: 45,
    studentAutonomyPct: 55,
    teacherAutonomyPct: 70,
    classSize: 20,
    masteryThresholdPct: 85,
    fundingPerStudentUSD: 17500,
    wellbeingFocusPct: 80,
    collaborativeLearningPct: 85,
    interdisciplinaryPct: 60
  },

  france_baccalaureat: {
    id: 'france_baccalaureat',
    name: 'France (Cartesian Baccalauréat Model)',
    presetId: 'france_baccalaureat',
    description: 'Rigorous secular academic curriculum, mandatory philosophy & critical essay analysis, centralized national Bac exam standards.',
    examWeightPct: 65,
    homeworkHoursPerDay: 3.5,
    aiIntegrationLevel: 35,
    studentAutonomyPct: 30,
    teacherAutonomyPct: 60,
    classSize: 28,
    masteryThresholdPct: 70,
    fundingPerStudentUSD: 12500,
    wellbeingFocusPct: 50,
    collaborativeLearningPct: 40,
    interdisciplinaryPct: 75
  },

  china_gaokao: {
    id: 'china_gaokao',
    name: 'China (Gaokao Meritocracy System)',
    presetId: 'china_gaokao',
    description: 'High-stakes Gaokao national entrance examination, intense study discipline, powerful social mobility engine, high STEM throughput.',
    examWeightPct: 92,
    homeworkHoursPerDay: 5.5,
    aiIntegrationLevel: 65,
    studentAutonomyPct: 10,
    teacherAutonomyPct: 20,
    classSize: 45,
    masteryThresholdPct: 88,
    fundingPerStudentUSD: 9500,
    wellbeingFocusPct: 25,
    collaborativeLearningPct: 35,
    interdisciplinaryPct: 25
  },

  india_nep2020: {
    id: 'india_nep2020',
    name: 'India (NEP 2020 Multidisciplinary Reform)',
    presetId: 'india_nep2020',
    description: 'Transition from rote 10+2 to 5+3+3+4 multidisciplinary model, early vocational integration, credit bank, high regional inclusivity.',
    examWeightPct: 40,
    homeworkHoursPerDay: 2.0,
    aiIntegrationLevel: 75,
    studentAutonomyPct: 60,
    teacherAutonomyPct: 70,
    classSize: 32,
    masteryThresholdPct: 75,
    fundingPerStudentUSD: 6500,
    wellbeingFocusPct: 75,
    collaborativeLearningPct: 70,
    interdisciplinaryPct: 90
  }
};
